In [1]:
import numpy as np 
arr = np.array([1,2,3,4,5]) 
rev_array = arr[::-1] 
print(rev_array)

[5 4 3 2 1]


In [2]:
arr_2 = np.array([[1,2,3], [2,4,5],[1,2,3]]) 
flatten = arr_2.flatten() 
print(flatten)


[1 2 3 2 4 5 1 2 3]


In [3]:
arr_1 = np.array([[1,2], [3,4]]) 
arr_2 = np.array([[1,2],[3,4]]) 
print(arr_1==arr_2)


[[ True  True]
 [ True  True]]


In [4]:
x = np.array([1,2,3,4,5,1,2,1,1,1]) 
counts_x = np.bincount(x) 
most_freq_x = np.argmax(counts_x) 
print(most_freq_x)

y = np.array([1,1,1,2,3,4,2,4,3,3]) 
counts_y = np.bincount(x) 
most_freq_y = np.argmax(counts_y)
print(most_freq_y)

1
1


In [7]:
gfg = np.matrix([[4,1,9],[12,3,6],[4,5,6]])
sum = np.sum(gfg)
sum_row = np.sum(gfg,axis = 1)
sum_col = np.sum(gfg,axis = 0)
print(sum)
print(sum_row)
print(sum_col)

50
[[14]
 [21]
 [15]]
[[20  9 21]]


In [8]:
n_array = np.array([[55,25,15],[30,44,2],[11,45,77]])
diagonal_sum_array = np.trace(n_array)
eigen_vals = np.linalg.eigvals(n_array)
eigen_vecs = np.linalg.eig(n_array)
inv_array = np.linalg.inv(n_array)
det_array = np.linalg.det(n_array)
print(diagonal_sum_array)
print(eigen_vals)
print(eigen_vecs)
print(inv_array)
print(det_array)

176
[98.16835147 28.097044   49.73460452]
EigResult(eigenvalues=array([98.16835147, 28.097044  , 49.73460452]), eigenvectors=array([[ 0.4574917 ,  0.34637121, -0.15017693],
       [ 0.28447814, -0.72784061, -0.4852124 ],
       [ 0.84248058,  0.59184038,  0.8614034 ]]))
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001


In [13]:
p = np.array([[1,2],[2,3]])
q = np.array([[4,5],[6,7]])
p_flat = p.flatten()
q_flat = q.flatten()
multiply_pq = np.dot(p,q)
cov_pq = np.cov(p_flat,q_flat)
print(multiply_pq)
print(cov_pq)

r = np.array([[1,2],[2,3],[4,5]])
s = np.array([[4,5,1],[6,7,2]])
r_flat = r.flatten()
s_flat = s.flatten()
multiply_rs = np.dot(r,s)
cov_rs = np.cov(r_flat,s_flat)
print(multiply_rs)
print(cov_rs)

[[16 19]
 [26 31]]
[[0.66666667 1.        ]
 [1.         1.66666667]]
[[16 19  5]
 [26 31  8]
 [46 55 14]]
[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [ ]:
from itertools import product
p = np.array([[2,3,4],[3,2,9]])
q = np.array([[1,5,0],[5,10,3]])
inner_pq = np.inner(p,q)
outer_pq = np.outer(p,q)
cartisian_product = np.array(list(product(p,q)))
print("Cartesian Produc:")
print(cartisian_product)
print("Inner Product:")
print(inner_pq)
print("Outer Product:")
print(outer_pq)

[[[ 2  3  4]
  [ 1  5  0]]

 [[ 2  3  4]
  [ 5 10  3]]

 [[ 3  2  9]
  [ 1  5  0]]

 [[ 3  2  9]
  [ 5 10  3]]]
Inner Product:
[[17 52]
 [13 62]]
Outer Product:
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]


In [30]:
array = np.array([[1,-2,3],[-4,5,-6]])
abs_values = np.abs(array)
print("Absolute:Value:")
print(abs_values)

flattened_array = array.flatten()

quartile_25 = np.percentile(flattened_array,25)
quartile_50 = np.percentile(flattened_array,50)
quartile_75 = np.percentile(flattened_array,75)

print("25th-Quartile:",quartile_25)
print("50th-Quartile:",quartile_50)
print("75th-Quartile:",quartile_75)

mean = np.mean(flattened_array)
median= np.median(flattened_array)
std = np.std(flattened_array)

print("Mean:",mean)
print("Median:",median)
print("Mode:",std)

# about each column axis= 0
mean_axis_0 = np.mean(array,axis=0)
median_axis_0= np.median(array,axis = 0)
std_axis_0 = np.std(array,axis = 0)

print("Mean about column:",mean_axis_0)
print("Median about column:",median_axis_0)
print("Mode about column:",std_axis_0)

# about each row axis= 1
mean_axis_1 = np.mean(array,axis=1)
median_axis_1= np.median(array,axis = 1)
std_axis_1 = np.std(array,axis = 1)

print("Mean about row:",mean_axis_1)
print("Median about row:",median_axis_1)
print("Mode about row:",std_axis_1)



Absolute:Value:
[[1 2 3]
 [4 5 6]]
25th-Quartile: -3.5
50th-Quartile: -0.5
75th-Quartile: 2.5
Mean: -0.5
Median: -0.5
Mode: 3.8622100754188224
Mean about column: [-1.5  1.5 -1.5]
Median about column: [-1.5  1.5 -1.5]
Mode about column: [2.5 3.5 4.5]
Mean about row: [ 0.66666667 -1.66666667]
Median about row: [ 1. -4.]
Mode about row: [2.05480467 4.78423336]


In [33]:
a = np.array([[-1.8,-1.6,-0.5,0.5,1.6,1.8,3.0]])
floor = np.floor(a)
ceil = np.ceil(a)
trunc = np.trunc(a)
round = np.round(a)
print("Floor:",floor)
print("Ceil:",ceil)
print("Truncated Values:",trunc)
print("Rounded Value:",round)

Floor: [[-2. -2. -1.  0.  1.  1.  3.]]
Ceil: [[-1. -1. -0.  1.  2.  2.  3.]]
Truncated Values: [[-1. -1. -0.  0.  1.  1.  3.]]
Rounded Value: [[-2. -2. -0.  0.  2.  2.  3.]]


In [38]:
array = np.array([10,52,62,16,16,54,453])
sorted_array = np.sort(array)
indices = np.argsort(array)
largest_5_ele = sorted_array[-1:-6:-1]
smallest_4_ele = sorted_array[:4]
print(sorted_array)
print(indices)
print(largest_5_ele)
print(smallest_4_ele)

array_2 = np.array([1.0,1.2,2.2,2.0,3.0,2.0])
int_elements = np.astype(array_2,int)
print(int_elements)
print(array_2)


[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[453  62  54  52  16]
[10 16 16 52]
[1 1 2 2 3 2]
[1.  1.2 2.2 2.  3.  2. ]
